[package]
name = "examples"
version = "0.0.1"
publish = false
edition = "2021"

[dependencies]
image = { version = "0.23.6", default-features = false }
ducat = { path = "../ducat" }

[[example]]
name = "test"
path = "test.rs"